name: 'ArgoCD Continuous Deployment'
description: ''
branding:
  icon: anchor
  color: orange
inputs:
  application:
    description: Application name on ArgoCD catalog
    required: false
  image:
    description: 'Image name (repo/name)'
    required: false
  image_tag:
    description: 'Image tag'
    required: true
    default: latest
  deployment_repo:
    description: 'Deployment repository'
    required: true
    default: 'totdev/applications'
  deployment_repo_token:
    description: 'Deployment repository token'
    required: true
    default: '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'
    #default: ${{ secrets.APPLICATIONS_REPO_TOKEN }}
  registry_user:
    description: 'Deployment repository'
    #default: 'deployc3'
    required: true
  registry_password:
    description: 'Deployment repository'
    required: true
  environment:
    description: 'Deployment environment'
    required: true
  yaml_file:
    description: 'Yaml that contains image tag info to be changed'
    required: false
    default: 'kustomization.yaml'
  yaml_file_image_tag_key:
    description: 'Image tag key in values.yaml'
    required: true
    default: 'images.0.newTag'
  context_path:
    description: 'Context Path'
    required: true
    default: '.'
  dockerfile:
    description: 'Dockerfile name'
    required: true
    default: 'Dockerfile'
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "docker"
  image: "Dockerfile"
