name: 'ArgoCD Continuous Deployment'
description: ''
branding:
  icon: anchor
  color: orange
inputs:
  application:
    description: Application name on ArgoCD catalog
    required: false
  image:
    description: Image name (repo/name)
    required: false
  image_tag:
    description: Image tag
    required: true
    default: latest
  deployment_repo:
    description: Deployment repository
    required: true
    default: 'totdev/applications'
  deployment_repo_token:
    description: Deployment repository token
    required: true
    default: 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
  registry_user:
    description: Deployment repository
    required: true
  registry_password:
    description: Deployment repository
    required: true
  environment:
    description: Deployment environment
    required: true
  yaml_file:
    description: Yaml that contains image tag info to be changed (ignored if is_openfaas_fn is true).
    required: false
    default: 'kustomization.yaml'
  context_path:
    description: Context Path (ignored if is_openfaas_fn is true).
    required: true
    default: '.'
  dockerfile:
    description: Dockerfile name
    required: true
    default: 'Dockerfile'
  is_openfaas_fn:
    description: Set to "true" if this repo is an openfaas fn.
    required: true
    default: 'false'
runs:
  using: "docker"
  image: "Dockerfile"
